---
- name: Tomcat deployment playbook
  hosts: all                # Inventory hosts group / server to act on
  become: yes               # If to escalate privilege
  #become_method: sudo       # Set become method
  #remote_user: root         # Update username for remote server
  vars:
    tomcat_ver: 8.5.69                         # Tomcat version to install
    ui_manager_user: tomcat                    # User who can access the UI manager section only
    ui_manager_pass: tomcat                     # UI manager user password
    ui_admin_username: tomcat                    # User who can access bpth manager and admin UI sections
    ui_admin_pass: tomcat                       # UI admin password
  roles:
    - tomcat

